performance_report.py

Generate comprehensive performance reports for Visual SLAM benchmarking.

import json
from pathlib import Path
from datetime import datetime
def generate_comprehensive_report(metrics: dict) -> str:
    """
    Generate a comprehensive text-based performance report.
    
    Args:
        metrics: Dictionary containing performance metrics
        
    Returns:
        Formatted text report
    """
    report = "=" * 80 + "\n"
    report += "VISUAL SLAM DEMO - COMPREHENSIVE PERFORMANCE REPORT\n"
    report += "=" * 80 + "\n\n"
    
    report += f"📊 EXECUTIVE SUMMARY\n"
    report += f"────────────────────\n"
    report += f"• Total Frames Processed: {metrics['frames_processed']:,}\n"
    report += f"• Keyframes Extracted: {metrics['keyframes_stored']:,}\n"
    report += f"• Loop Closures Detected: {metrics['loop_closures_detected']:,}\n"
    report += f"• Final Trajectory Accuracy: {metrics['refined_drift_m']:.3f} m drift\n"
    report += f"• Performance Grade: {'A' if metrics['refined_drift_m'] < 0.5 else 'B' if metrics['refined_drift_m'] < 1.5 else 'C'}\n\n"
    
    report += f"🧪 DETAILED PERFORMANCE METRICS\n"
    report += f"────────────────────\n"
    report += f"🖥 Raw Performance:\n"
    report += f"   • Initial Drift: {metrics['initial_drift_m']:.3f} m\n"
    report += f"   • Refined Drift: {metrics['refined_drift_m']:.3f} m\n"
    report += f"   • Total Reduction: {metrics['drift_reduction_percentage']:.1f}%\n"
    report += f"   • Loop Closure Interval: {metrics['average_loop_closure_interval']:.1f} frames\n\n"
    
    report += f"📊 Perception Quality:\n"
    report += f"   • Average Inlier Ratio: {metrics['average_inlier_ratio']:.3f}\n"
    report += f"   • Range: [{metrics['min_inlier_ratio']:.3f}, {metrics['max_inlier_ratio']:.3f}]\n"
    report += f"   • Average Feature Count: {metrics['average_feature_count']:.1f}\n"
    report += f"   • Range: [{metrics['min_feature_count']}, {metrics['max_feature_count']}]\n\n"
    
    report += f"🏆 Comparative Analysis (Synthetic vs Real Data)\n"
    report += f"────────────────────\n"
    synth = metrics["benchmark_summary"]["synthetic_performance"]
    real = metrics["benchmark_summary"]["real_data_performance"]
    gaps = metrics["benchmark_summary"]["performance_gaps"]
    
    report += f"SYNTHETIC MODE:\n"
    report += f"   • Final Drift: {synth['final_drift_m']} m\n"
    report += f"   • Drift Reduction: {synth['drift_reduction_pct']}%\n"
    report += f"   • Loop Closure Rate: {synth['loop_closure_rate']}\n"
    report += f"   • Feature Precision: {synth['feature_precision']}\n\n"
    
    report += f"REAL DATA MODE:\n"
    report += f"   • Final Drift: {real['final_drift_m']} m\n"
    report += f"   • Drift Reduction: {real['drift_reduction_pct']}%\n"
    report += f"   • Loop Closure Rate: {real['loop_closure_rate']}\n"
    report += f"   • Feature Precision: {real['feature_precision']}\n\n"
    
    report += f"PERFORMANCE GAPS:\n"
    report += f"   • Drift Improvement Difference: {gaps['drift_improvement_difference']:.1f}%\n"
    report += f"   • Reliability Equivalence: {'✅ Yes' if gaps['reliability_equivalence'] else '❌ No'}\n"
    report += f"   • Precision Equivalence: {'✅ Yes' if gaps['precision_equivalence'] else '❌ No'}\n\n"
    
    report += f"🔑 KEY RESEARCH INSIGHTS\n"
    report += f"────────────────────\n"
    for i, insight in enumerate(metrics['benchmark_summary']['key_insights'], 1):
        report += f"{i}. {insight}\n\n"
    
    report += f"🏆 RESEARCH APPLICATION SCORES\n"
    report += f"────────────────────\n"
    for category, score in metrics['research_application_score'].items():
        category_name = category.replace('_', ' ').title()
        report += f"• {category_name}: {score*100:.0f}%\n"
    
    report += f"\n✅ QUALITY GATE STATUS\n"
    report += f"────────────────────\n"
    for gate, status in metrics['quality_gate_status'].items():
        symbol = "✅" if status else "❌"
        gate_name = gate.replace('_', ' ').title()
        report += f"{symbol} {gate_name}: {'Pass' if status else 'Fail'}\n"
    
    report += f"\n"
    report += f"=" * 80 + "\n"
    report += f"END OF PERFORMANCE REPORT - Generated by Enhanced Metrics System\n"
    report += f"=" * 80
    return report


def create_html_summary(metrics: dict, output_path: str) -> None:
    """
    Create HTML format with embedded visualization.
    
    Args:
        metrics: Dictionary containing performance metrics
        output_path: Path to save the HTML file
    """
    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>Visual SLAM Demo - Performance Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        .header {{ background-color: #2c3e50; color: white; padding: 20px; border-radius: 5px; }}
        .metric {{ background-color: #f8f9fa; padding: 15px; margin: 10px; border-radius: 3px; border-left: 4px solid #007bff; }}
        .insight {{ background-color: #d4edda; padding: 10px; margin: 5px; border-radius: 3px; }}
        .warning {{ background-color: #fff3cd; padding: 10px; margin: 5px; border-radius: 3px; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 週; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #f2f2f2; }}
    </style>
</head>
<body>
    <div class=\"header\">
        <h1>🚀 Visual SLAM Demo - Performance Analysis Report</h1>
        <p>Generated on {metrics['metadata']['generated_at']}</p>
    </div>

    <div class=\"metric\">
        <h2>📊 Executive Summary</h2>
        <p><strong>Total Frames Processed:</strong> {metrics['frames_processed']}</p>
        <p><strong>Keyframes Extracted:</strong> {metrics['keyframes_stored']}</p>
        <p><strong>Loop Closures Detected:</strong> {metrics['loop_closures_detected']}</p>
        <p><strong>Final Trajectory Accuracy:</strong> {metrics['refined_drift_m']:.3f} m drift</p>
    </div>

    <div class=\"metric\">
        <h2>🧪 Performance Comparison</h2>
        <table>
            <tr><th>Mode</th><th>Final Drift (m)</th><th>Drift Reduction (%)</th><th>Loop Closure Rate</th></tr>
            <tr>
                <td>Synthetic</td>
                <td>{metrics['benchmark_summary']['synthetic_performance']['final_drift_m']}</td>
                <td>{metrics['benchmark_summary']['synthetic_performance']['drift_reduction_pct']}%</td>
                <td>{metrics['benchmark_summary']['synthetic_performance']['loop_closure_rate']}</td>
            </tr>
            <tr>
                <td>Real Data</td>
                <td>{metrics['benchmark_summary']['real_data_performance']['final_drift_m']}</td>
                <td>{metrics['benchmark_summary']['real_data_performance']['drift_reduction_pct']}%</td>
                <td>{metrics['benchmark_summary']['real_data_performance']['loop_closure_rate']}</td>
            </tr>
        </table>
    </div>

    <div class=\"insight\">
        <h2>🔑 Key Insights</h2>
        <ul>
"""
    for insight in metrics['benchmark_summary']['key_insights']:
        html += f"            <li>{insight}</li>\n"
    
    html += """
        </ul>
    </div>

    <div class=\"warning\">
        <h2>⚠️ Quality Gates Status</h2>
        <ul>
"""
    for gate, status in metrics['quality_gate_status'].items():
        symbol = "✅" if status else "❌"
        gate_name = gate.replace('_', ' ').title()
        html += f"            <li>{symbol} {gate_name}: {'Pass' if status else 'Fail'}</li>\n"
    
    html += """
        </ul>
    </div>

    <div class=\"metric\">
        <h2>🏆 Research Application Scores</h2>
        <ul>
"""
    for category, score in metrics['research_application_score'].items():
        category_name = category.replace('_', ' ').title()
        html += f"            <li><strong>{category_name}:</strong> {score*100:.0f}%</li>\n"
    
    html += """
        </ul>
    </div>

    <footer>
        <p><em>Generated by Visual SLAM Demo v1.0 | Enhanced with Comprehensive Metrics</em></p>
    </footer>
</body>
</html>
"""
    
    with open(output_path, 'w') as f:
        f.write(html)


def create_metrics_csv(metrics: dict, output_path: str) -> None:
    """
    Create CSV format for easy analysis.
    
    Args:
        metrics: Dictionary containing performance metrics
        output_path: Path to save the CSV file
    """
    import pandas as pd
    
    # Key performance indicators as rows
    rows = []
    
    # Basic metrics
    rows.append({
        'Category': 'Basic Performance',
        'Metric': 'Frames Processed',
        'Value': metrics['frames_processed']
    })
    rows.append({
        'Category': 'Basic Performance',
        'Metric': 'Keyframes Stored',
        'Value': metrics['keyframes_stored']
    })
    rows.append({
        'Category': 'Basic Performance',
        'Metric': 'Loop Closures Detected',
        'Value': metrics['loop_closures_detected']
    })
    
    # Trajectory accuracy
    rows.append({
        'Category': 'Trajectory Accuracy',
        'Metric': 'Initial Drift (m)',
        'Value': metrics['initial_drift_m']
    })
    rows.append({
        'Category': 'Trajectory Accuracy',
        'Metric': 'Final Drift (m)',
        'Value': metrics['refined_drift_m']
    })
    rows.append({
        'Category': 'Trajectory Accuracy',
        'Metric': 'Drift Reduction (%)',
        'Value': metrics['drift_reduction_percentage']
    })
    
    # Perception metrics
    rows.append({
        'Category': 'Perception Quality',
        'Metric': 'Average Inlier Ratio',
        'Value': metrics['average_inlier_ratio']
    })
    rows.append({
        'Category': 'Perception Quality',
        'Metric': 'Average Feature Count',
        'Value': metrics['average_feature_count']
    })
    
    # Benchmark comparison
    synth = metrics['benchmark_summary']['synthetic_performance']
    real = metrics['benchmark_summary']['real_data_performance']
    gaps = metrics['benchmark_summary']['performance_gaps']
    
    rows.append({
        'Category': 'Benchmark Comparison',
        'Metric': 'Synthetic Final Drift (m)',
        'Value': synth['final_drift_m']
    })
    rows.append({
        'Category': 'Benchmark Comparison',
        'Metric': 'Real Data Final Drift (m)',
        'Value': real['final_drift_m']
    })
    rows.append({
        'Category': 'Benchmark Comparison',
        'Metric': 'Drift Improvement Difference',
        'Value': gaps['drift_improvement_difference']
    })
    
    # Research scores
    for category, score in metrics['research_application_score'].items():
        category_name = category.replace('_', ' ').title()
        rows.append({
            'Category': 'Research Application',
            'Metric': f'{category_name}',
            'Value': f'{score*100:.0f}%'
        })
    
    # Create DataFrame and save
    df = pd.DataFrame(rows)
    df.to_csv(output_path, index=False)


if __name__ == "__main__":
    # Example usage
    print("This module provides functions to generate comprehensive performance reports.")
    print("Import functions: generate_comprehensive_report, create_html_summary, create_metrics_csv")
